"""
audio_constants.py
This file defines configuration constants for the audio processing pipeline.
It handles TTS (Text-To-Speech) model configurations and ONVIF/RTSP camera audio streaming parameters.
"""

# ==========================================
# KittenTTS Configuration
# These constants define the behavior and characteristics of the local Text-To-Speech engine.
# ==========================================

KITTEN_TTS_MODEL = "KittenML/kitten-tts-nano-0.8"   # HuggingFace path to the lightweight TTS model
DEFAULT_TTS_VOICE = "Luna"                          # The default voice persona used for audio alerts
DEFAULT_TTS_SPEED = 1.5                             # Playback speed multiplier (1.0 is normal speed)
KITTEN_TTS_SAMPLE_RATE = 24000                      # Output sample rate in Hz generated by the TTS model

# ==========================================
# ONVIF / Dahua Camera Push Configuration
# These constants are used to encode the generated TTS audio into a format 
# that the camera's two-way audio (backchannel) accepts.
# ==========================================

ONVIF_AUDIO_SAMPLE_RATE = "8000"                    # Required sample rate for standard security camera audio backchannels
ONVIF_AUDIO_CODEC = "pcm_mulaw"                     # G.711 mu-law codec, widely supported by IP cameras
ONVIF_AUDIO_CHANNELS = "1"                          # Mono audio channel
FFMPEG_TIMEOUT_SEC = 10                             # Maximum timeout in seconds when streaming audio to the camera
